name: Daily post to channel

on:
  schedule:
    - cron: "15 23 * * *"
  workflow_dispatch:

jobs:
  daily_message:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv

      - name: Install dependencies
        run: |
          make install

      - name: Send message to prod channel
        run: |
          pipenv run python main.py ${{secrets.TELEGRAM_TOKEN}} @pvpc_report
